### ISSUE TITLE
error: "runInteractiveProcess:exec:does not exist"

### ISSUE THREAD

**Issue by lihpsg** [GregorySchwartz/too-many-cells#11]
Encountered the following error when running "make-tree": 

"twopi: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)"

The command I used was: 
~/.local/bin/too-many-cells make-tree -m ~/too-many-cells/filtered_feature_bc_matrix --draw-collection "PieRing" -- output out >clusters.csv

**Comment by GregorySchwartz** [comment]
Please re-open if this answer did not solve your question!

**Comment by lihpsg** [comment]
Thank! installation of graphviz addressed this issue.
