### ISSUE TITLE
Error when running too-many-cells

### ISSUE THREAD

**Issue by zhaixzh** [GregorySchwartz/too-many-cells#15]
Hi @GregorySchwartz , I use the image for too-many-cells, but when I run make-tree, I met an error :

Loading matrix []   0%too-many-cells: ./Data/Vector/Generic.hs:245 ((!)): index out of bounds (0,0)
CallStack (from HasCallStack):
  error, called at ./Data/Vector/Internal/Check.hs:87:5 in vector-0.12.0.1-GGZqQZyzchy8YFPCF67wxL:Data.Vector.Internal.Check

When I use docker，whether additional stack installation is required ?

**Comment by GregorySchwartz** [comment]
This might be because all cells were filtered out. Did you check your (or the default) `--filter-thresholds` (or use `--no-filter`), and whitelist.

**Comment by GregorySchwartz** [comment]
Did this resolve your issue?
