### ISSUE TITLE
error message during installation of too-many-cells on ubuntu

### ISSUE THREAD

**Issue by zmokhtari** [GregorySchwartz/too-many-cells#16]
I am trying to install too-many-cells on Ubuntu 19.4. I am facing this error message:
"--  While building package glib-0.13.6.0 using:
      /tmp/stack24744/glib-0.13.6.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 211/248"
Could you please help me to solve the issue?
Thanks in advance,
Zeinab

**Comment by GregorySchwartz** [comment]
This issue is solved with newer `glib` releases. I updated `glib` here, so pull the new version and try to install again (and let me know if it works).

**Comment by zmokhtari** [comment]
thanks for your fast response. Installation worked fine, however, when I try the example in R I get this error : "sh: 1: too-many-cells: not found
Error in system2("too-many-cells", args = c(args, autoArgs), stdout = TRUE) : 
  error in running command
In addition: Warning message:
In dir.create(output, recursive = TRUE) : 'out' already exists"
I should mention that I installed toomanycellsR first and then I installed too-many-cells.

**Comment by GregorySchwartz** [comment]
Docker or from source?

**Comment by zmokhtari** [comment]
I have both, but I want to use the source.

**Comment by GregorySchwartz** [comment]
Is `too-many-cells` in your path? It should be in `~/.local/bin`.

**Comment by zmokhtari** [comment]
Yes, it is:
Copied executables to /home/zeinab/.local/bin:
- too-many-cells

**Comment by GregorySchwartz** [comment]
Is `/home/zeinab/.local/bin` in your `$PATH`?

**Comment by zmokhtari** [comment]
Yes, I double checked, it is in my $PATH list.

**Comment by GregorySchwartz** [comment]
Ah, so `which too-many-cells` is returning a result? I keep bringing this up because `sh: 1: too-many-cells: not found` means that your shell cannot find the command. If `which too-many-cells` does return a result, then there must be some disconnect between R and your shell.

**Comment by zmokhtari** [comment]
It returns"/home/zeinab/.local/bin/too-many-cells". Could you please help me to check the connection between R and the shell?

**Comment by GregorySchwartz** [comment]
Interesting. Can you open R in your home folder and run `system2("too-many-cells", stdout = TRUE)`? Then open R in your `~/.local/bin` folder and do the same?

**Comment by zmokhtari** [comment]
thank you for your help. 
both of them return: "Missing: (make-tree | interactive | differential | diversity | paths)

Usage: too-many-cells (make-tree | interactive | differential | diversity |
                      paths)
character(0)
attr(,"status")
[1] 1
Warning message:
In system2("too-many-cells", stdout = TRUE) :
  running command ''too-many-cells'' had status 1
"

**Comment by GregorySchwartz** [comment]
So it can find the command in both cases, but in the `tooManyCell()` function in those same sessions it does not find the command?

**Comment by zmokhtari** [comment]
That is right! Still I could not solve the issue.

**Comment by GregorySchwartz** [comment]
This may be beyond my understanding. The `tooManyCells()` function uses `system2("too-many-cells")` with no changing of directories, so I don't know what to do if `system2` works outside of the function but not inside. My suggestion would be to just call it outside of the function or use the command line program.

**Comment by zmokhtari** [comment]
Thanks for your suggestions. I used the command line for the example data and it worked fine, I am wondering if I provide cytof data in csv format, whether too many cells is accepting that format? Do I need to provide gene names and cell IDs too? Can I send you an example of the csv format that you could examine the format of the file? Thanks in advance.

**Comment by GregorySchwartz** [comment]
You can use csv format, just input it with `-m data.csv`. The format is a normal csv file, with a header for the name of the column (cell) and an initial column containing the features as the first column. With this data, don't forget to change the default normalization and filters (I would recommend something like `--normalization UQNorm` and `-F` for no filtering)!

**Comment by zmokhtari** [comment]
Thank you very much for your help. It works fine.

**Comment by zmokhtari** [comment]
Hi Gregory, 
I am wondering if I provide gene.csv file for the list of features that is measured, how can I point to a specific gene when I want to color the dendrogram based on a gene expression level? thanks

**Comment by GregorySchwartz** [comment]
The instructions would be the same as on the website (https://gregoryschwartz.github.io/too-many-cells/) under "gene expression". Although you wouldn't have a "genes" file, you just load in the matrix you used earlier to create the tree.

**Comment by zmokhtari** [comment]
Thanks for your help.

**Comment by GregorySchwartz** [comment]
My pleasure!
