### ISSUE TITLE
Runing too-many-cell's Docker 'gregoryschwartz/too-many-cells' occurred error on the middle of procedure

### ISSUE THREAD

**Issue by honghh2018** [GregorySchwartz/too-many-cells#20]
Hi @GregorySchwartz 
      Thanks for developing the great tools for single cell analysis.
       The error would be triggered when running the docker of gregoryschwartz/too-many-cells using following command 'docker run -it --rm -v //share/nas1/Data/Users/user/Personalization/20191206_ana/20200319_mainline/result/integrated/vst/subtypes/T_cells/TooManyCells/:/input_matrix gregoryschwartz/too-many-cells:0.2.2.0 make-tree --matrix-path /input_matrix/T_cells.csv -l /input_matrix/T_cells_ann.csv -o ./out' 
       The error picture showing below:
        
![image](https://user-images.githubusercontent.com/41668708/78753656-c1bbd300-79a8-11ea-8d68-21c1310ffb21.png)
       I am confusing utterly that why the error just broke down in middle step of runing on 70% but  the begin of the runing of docker.
      That whether It was meaning that the inputted file i provided was right, so what happen to my 
      running of this situation.
      Thanks
       Any advice would be appreciated
       System:
       CentOS Linux release 7.3.1611 (Core)
       the input file format display below:
       cell annotation :
![image](https://user-images.githubusercontent.com/41668708/78754485-1f9cea80-79aa-11ea-8ca9-98bce398086c.png)
       expression matrix:
       
![image](https://user-images.githubusercontent.com/41668708/78754522-36434180-79aa-11ea-881a-2145ead8032d.png)

**Comment by GregorySchwartz** [comment]
That just means that the cell barcode specified was not assigned a label. As a result, `too-many-cells` lets you know that the clumpiness measure can't be calculated, but that's optional. You should still see the output, just no clumpiness plot. You might want to change your docker mounts, though, as you did not mount `.` so you are outputting to `./out` when you probably want `./input_matrix/out` or something like that.

**Comment by GregorySchwartz** [comment]
Did this solve your issue?

**Comment by honghh2018** [comment]
Hi @GregorySchwartz  
   The problem i posted before had solved yet.
    But i had a question that the too-many-cell docker  runing single cell data,size 32001x43111 matrix, have last for a few day and now it remained on runing status but stop. the picture showing below:
    Is this norm? or abnormal.
     Your advices would be appreciated.
      Thanks
![image](https://user-images.githubusercontent.com/41668708/79035945-b7dadf80-7bf5-11ea-9da7-cda182f3e788.png)

**Comment by GregorySchwartz** [comment]
I don't know the stats of your computer, but I would let it run to completion. If you want a faster result, I would recommend dimensionality reduction (as I could get millions of cells in the tree in an hour on my setup).
