### ISSUE TITLE
Normalization section in too-many-cells differential -h

### ISSUE THREAD

**Issue by kuang-da** [GregorySchwartz/too-many-cells#23]
Hi,

Thanks for building such a nice tool. But I am a bit confused about the normalization in the differential analysis component. The help page does not help much since it basically identical to the help page of make-tree.

It seems so far the too-many-cell pipeline run two normalization algorithm: one before clustering and the other before DE analysis. By default, the normalization before clustering is TfIdfNorm and the normalization is NoneNorm so that the program will revoke edgeR's normalization algorithm. Is my understanding right?

I guess my question is to double-check the function of --normalization argument in `too-many-cells differential`. May I assume it is used to choose the normalization algorithm before DE and by default is should be NoneNorm?

Currently, the Normalization section in the help page of `too-many-cells differential` is identical, which makes me feel like I am choosing an algorithm for clustering.

Thanks for your time!

**Comment by GregorySchwartz** [comment]
This issue is due to a limitation in `optparse-generic` unfortunately https://github.com/Gabriel439/Haskell-Optparse-Generic-Library/issues/60.

**Comment by kuang-da** [comment]
Mark as resolved. Thank you!
