### ISSUE TITLE
parse error (not enough input)

### ISSUE THREAD

**Issue by acpandey** [GregorySchwartz/too-many-cells#31]
I am trying to run on docker with a windows 10 system.  not sure if my system is running out of memory or there is another issue. Thinking it is not only a memory issue since usually that has not thrown an error for me in the past. 

C:\Users\acpan
λ docker run -i --rm -v C:\Users\acpan\too-many-cells\too-many-cells\filtered_feature_bc_matrix\:/filtered_feature_bc_matrix/ gregoryschwartz/too-many-cells:0.2.2.0 make-tree --no-filter --normalization NoneNorm --draw-max-node-size 40 --draw-max-leaf-node-size 70 --matrix-path /filtered_feature_bc_matrix/ --output /filtered_feature_bc_matrix/out/ --labels-file /filtered_feature_bc_matrix/labels.csv
Recording tree measurements [======================>......................]  50%too-many-cells: parse error (not enough input) at ""
CallStack (from HasCallStack):
  error, called at src/BirchBeer/Load.hs:45:33 in birch-beer-0.2.2.0-GoLgVIKGefMG9Opfue2NME:BirchBeer.Load

C:\Users\acpan
λ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 9
 Total Memory: 47.07GiB
 Name: docker-desktop
 ID: NX5S:K2SQ:E262:C2MZ:XI77:FYJP:HN54:MNWC:LENB:BKF5:HRBU:HYKF
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 54
  System Time: 2020-07-27T17:53:04.461267527Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by GregorySchwartz** [comment]
Looks like the `labels.csv` file is not formatted correctly. You might have a column mismatch, an empty line, etc.

**Comment by acpandey** [comment]
thanks worked. had redone the ``labels.csv`` file and forgotten to add the header line.

**Comment by GregorySchwartz** [comment]
Great to hear it worked!
