### ISSUE TITLE
Error in installing with docker

### ISSUE THREAD

**Issue by huangxingnan1994** [GregorySchwartz/too-many-cells#32]
Hi,

I am getting trouble with installing with docker, when I run `docker pull gregoryschwartz/too-many-cells:2.0.0.0`. I always get error like this:

`Error response from daemon: Get https://registry-1.docker.io/v2/gregoryschwartz/too-many-cells/manifests/2.0.0.0: Get https://auth.docker.io/token?scope=repository%3Agregoryschwartz%2Ftoo-many-cells%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Thanks so much!

**Comment by GregorySchwartz** [comment]
Looks like you are having trouble connecting to Docker's servers. Maybe try again later? Do you have any DNS issues (https://github.com/docker/for-win/issues/1534)?

**Comment by huangxingnan1994** [comment]
Thanks
The issue has gone away after changing DNS sever
