### ISSUE TITLE
Running a million cells failed in the docker

### ISSUE THREAD

**Issue by minghlijiyi** [GregorySchwartz/too-many-cells#34]
Hi Gregory, I installed the package in the docker. I gave 15g RAM to the docker, it is the maximum RAM.  It runs well for 500,000 cells, However, it runs failed for a million cells. Could you give me some help? I used the below codes. Thank you.
docker run -it --rm -v "/home/username:/home/username" \
    -m 15g \
    gregoryschwartz/too-many-cells:2.0.0.0 make-tree \
    --matrix-path /home/username/path/to/input \
    --labels-file /home/username/path/to/labels.csv \
    --draw-collection "PieRing" \
    --output /home/username/path/to/out \
    > clusters.csv

**Comment by GregorySchwartz** [comment]
`too-many-cells` will try to use all features for the most accurate result. However, with many cells this will take even more time and space. I recommend using dimensionality reduction to reduce the feature space upstream of `too-many-cells`, or try using the built in one (`--lsa`) to see if it can handle it first.

**Comment by minghlijiyi** [comment]
It works, thank you so much!
