### ISSUE TITLE
fail when downloading ucsc browser

### ISSUE THREAD

**Issue by chansigit** [GregorySchwartz/too-many-cells#43]
i am using nix to install too-many-cells on my ubuntu 20 server, when i cloned the github repository and run nix-env -f default.nix -i too-many-cells, I always get the following error codes, what should I do?

Installing library in /nix/store/qyzrysq5rvfjlcg5x608w9rjaa2zw7xh-modularity-0.2.1.1/lib/ghc-8.10.4/x86_64-linux-ghc-8.10.4/modularity-0.2.1.1-IqGSQGN5D2q2AdgZmiJt0X
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/qyzrysq5rvfjlcg5x608w9rjaa2zw7xh-modularity-0.2.1.1
shrinking /nix/store/qyzrysq5rvfjlcg5x608w9rjaa2zw7xh-modularity-0.2.1.1/lib/ghc-8.10.4/x86_64-linux-ghc-8.10.4/libHSmodularity-0.2.1.1-IqGSQGN5D2q2AdgZmiJt0X-ghc8.10.4.so
strip is /nix/store/8xiqj7nkx1z0mxhda9pcl8fa51zmxqd1-binutils-2.35.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/qyzrysq5rvfjlcg5x608w9rjaa2zw7xh-modularity-0.2.1.1/lib 
patching script interpreter paths in /nix/store/qyzrysq5rvfjlcg5x608w9rjaa2zw7xh-modularity-0.2.1.1
checking for references to /build/ in /nix/store/qyzrysq5rvfjlcg5x608w9rjaa2zw7xh-modularity-0.2.1.1...
shrinking RPATHs of ELF executables and libraries in /nix/store/2md5vngjf8cz3hmb8xh2kf985dbwfvim-modularity-0.2.1.1-doc
strip is /nix/store/8xiqj7nkx1z0mxhda9pcl8fa51zmxqd1-binutils-2.35.1/bin/strip
patching script interpreter paths in /nix/store/2md5vngjf8cz3hmb8xh2kf985dbwfvim-modularity-0.2.1.1-doc
checking for references to /build/ in /nix/store/2md5vngjf8cz3hmb8xh2kf985dbwfvim-modularity-0.2.1.1-doc...
building '/nix/store/7f2mn29swi2l69ffzrx8s5d9f913jq5h-source.drv'...

trying https://github.com/ucscGenomeBrowser/kent/archive/v404_base.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
curl: (52) Empty reply from server
error: cannot download source from any mirror
error: builder for '/nix/store/7f2mn29swi2l69ffzrx8s5d9f913jq5h-source.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://github.com/ucscGenomeBrowser/kent/archive/v404_base.tar.gz
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
       > curl: (52) Empty reply from server
       > error: cannot download source from any mirror
       For full logs, run 'nix log /nix/store/7f2mn29swi2l69ffzrx8s5d9f913jq5h-source.drv'.
error: 1 dependencies of derivation '/nix/store/cv85fnqllsy0ps8a40wbdr5ggh3v9bvr-kent-404.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x2i34nk8ljfaammqxgv5rmjg6by5wf5n-too-many-cells-2.2.1.0.drv' failed to build

**Comment by GregorySchwartz** [comment]
The link is available to reach from my end, maybe the server was temporarily down?

**Comment by GregorySchwartz** [comment]
Let me know if you continue to see this behavior as I do not, closing.
