### ISSUE TITLE
The pipeline crashed with error message

### ISSUE THREAD

**Issue by smarhon** [GregorySchwartz/too-many-cells#44]

**Comment by smarhon** [comment]
I am trying to run the pipeline on the cluster, but the pipeline crashes with this error message. too-many-cells: /scratch/3950086: openTempFile: does not exist (No such file or directory). Does it mean the pipeline could not create temporary folder/file?

**Comment by GregorySchwartz** [comment]
It is likely that you do not have permission for the current $TMPDIR, try changing that variable in your shell or script to some other directory to store temporary files. Either permanently in your `~/.bashrc` or temporarily: `export TMPDIR=/path/to/a/directory/you/own`.

**Comment by smarhon** [comment]
Thanks! yes, that solved the problem. It was permission issue.
