### ISSUE TITLE
too-many-cells not installed on MacOSX Sierra

### ISSUE THREAD

**Issue by UserBio2019** [GregorySchwartz/too-many-cells#5]
I tried to install too-many-cells on MacOS X Sierra without success. 

It fails building gtk 0.14 that is required. 

I also followed instructions here: https://wiki.haskell.org/Gtk2Hs/Mac i.e. I tried 
to use cabal install gtk -f have-quartz-gtk although for OS X Mavericks but again it failed. 

It installs automatically gtk 0.15. 

Any suggestion?

Thank you in advance

**Comment by GregorySchwartz** [comment]
Can you post the error output?

**Comment by UserBio2019** [comment]
Yes: 

gtk-0.14.10: configure
gtk-0.14.10: build
Progress 1/5

--  While building package gtk-0.14.10 using:
      /private/var/folders/lv/2jj3qhdn7wz4t58kgm0m14bmgc_64f/T/stack-aaff458a906ff1bc/gtk-0.14.10/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.2.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

In the attached log file the details.

Thank you in advance

[gtk-0.14.10.log](https://github.com/GregorySchwartz/too-many-cells/files/2927186/gtk-0.14.10.log)

**Comment by GregorySchwartz** [comment]
I don't have a Mac so FYI I won't have a way to test this (worst case scenario you can use docker which won't have these issues).

First, did you use this command in the `too-many-cells` folder with stack? Something like `stack install --ghc-options "have-quartz-gtk"`.

**Comment by GregorySchwartz** [comment]
Also try `stack install --flag gtk:have-quartz-gtk` from https://github.com/commercialhaskell/stack/issues/807.

**Comment by UserBio2019** [comment]
So while solved the gtk-0.14.10 build another error occurs: 

Building library for too-many-cells-0.1.3.0..
[ 3 of 21] Compiling TooManyCells.Matrix.Types ( src/TooManyCells/Matrix/Types.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/TooManyCells/Matrix/Types.o )
<command line>: can't load .so/.DLL for: /Users/Username/.stack/snapshots/x86_64-osx/lts-12.0/8.4.3/lib/x86_64-osx-ghc-8.4.3/libHShmatrix-gsl-0.19.0.1-Gni665xmjpQJJA5D3St61G-ghc8.4.3.dylib (dlopen(/Users/lusito.eleonora/.stack/snapshots/x86_64-osx/lts-12.0/8.4.3/lib/x86_64-osx-ghc-8.4.3/libHShmatrix-gsl-0.19.0.1-Gni665xmjpQJJA5D3St61G-ghc8.4.3.dylib, 5): Library not loaded: /usr/local/opt/gsl/lib/libgsl.23.dylib
  Referenced from: /Users/Username/.stack/snapshots/x86_64-osx/lts-12.0/8.4.3/lib/x86_64-osx-ghc-8.4.3/libHShmatrix-gsl-0.19.0.1-Gni665xmjpQJJA5D3St61G-ghc8.4.3.dylib
  Reason: image not found)

**Comment by GregorySchwartz** [comment]
Do you have the GNU Scientific Library dependency? If not first install that and the rest of the dependencies in the installation section of https://gregoryschwartz.github.io/too-many-cells/. I don't know the exact names of the Mac equivalents. If it still doesn't work, let me know!

**Comment by GregorySchwartz** [comment]
Any updates or should I close this issue?

**Comment by UserBio2019** [comment]
still not working. we stopped trying to install it

**Comment by GregorySchwartz** [comment]
That's unfortunate. I will try to get hold of a Mac to try and sort this out. In the meantime, have you tried the Docker? Mac people have had success using that instead of compiling from scratch.

**Comment by UserBio2019** [comment]
Oh yes Docker! So, I cannot use it on our cluster because it is installed on a dedicated server and in development and we, users, don't have access. I then installed it on my Mac but since I deal with 30.000 cells I have some resources issues. Probably I can try using a subset of cells at least to verify that it works.

**Comment by GregorySchwartz** [comment]
I was able to build on macOS with no issue using the commands I put into the documentation in Installation -> macOS (https://gregoryschwartz.github.io/too-many-cells/). Please try it out and see if it solves your problem!

**Comment by GregorySchwartz** [comment]
It works on this end, so if you are still having difficulty please re-open this issue.
