### ISSUE TITLE
How to modify the colors of the PieChart

### ISSUE THREAD

**Issue by yanglq-bioinfo** [GregorySchwartz/too-many-cells#50]
Hello,
Thanks for your packages.After running make-tree,I get the plot.It's  beautiful,but I want to know,if I can change the PieChart's colors use my selected colors.I find there is a Parameter which is --draw-palette,but I have to choose between Set1 | HSV | Ryb | Blues.Can I use a custom colors?

**Comment by GregorySchwartz** [comment]
This is possible, see custom colors in https://gregoryschwartz.github.io/too-many-cells/workshop/workshop.html

Through `--draw-colors`.
