### ISSUE TITLE
Running too-many-cells with normalized data

### ISSUE THREAD

**Issue by ghoshal** [GregorySchwartz/too-many-cells#7]
Hi Greg,

I have normalized data from my scRNAseq analysis pipeline that I would like to use with too-many-cells for hierarchical clustering and creating a tree. How can I do that?

Thanks

**Comment by GregorySchwartz** [comment]
Do you mean what options to use? Because your data is preprocessed, you should supply `--no-filter` and `--normalization NoneNorm` in order to bypass the default filtering and normalization that TooManyCells does.

**Comment by ghoshal** [comment]
Thanks Greg. Also, is there a specific format for the label file? I have cells from two different conditions that I want to plot on the tree.

**Comment by GregorySchwartz** [comment]
The **setup** section in the `make-tree` usage section of the documentation (https://gregoryschwartz.github.io/too-many-cells/) has the required formats for each file.
